# Opens Supabase SQL migration instructions (tables required for full profile storage)
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$Sql001 = Join-Path $RepoRoot "supabase\migrations\001_profiles_auth.sql"
$Sql002 = Join-Path $RepoRoot "supabase\migrations\002_collab_and_messages.sql"
$Sql003 = Join-Path $RepoRoot "supabase\migrations\003_ensure_conversation_rpc.sql"
$Sql004 = Join-Path $RepoRoot "supabase\migrations\004_user_presence.sql"
$Sql005 = Join-Path $RepoRoot "supabase\migrations\005_presence_typing.sql"
$Sql006 = Join-Path $RepoRoot "supabase\migrations\006_campaign_projects.sql"
$Sql008 = Join-Path $RepoRoot "supabase\migrations\008_fix_register_profile_role.sql"
$Sql009 = Join-Path $RepoRoot "supabase\migrations\009_public_influencer_profile.sql"
$Sql010 = Join-Path $RepoRoot "supabase\migrations\010_business_approval_status.sql"
$Sql011 = Join-Path $RepoRoot "supabase\migrations\011_business_profile_extras.sql"
$ProjectUrl = "https://supabase.com/dashboard/project/hrpaqufvjcihnjrjnpej/sql/new"

Write-Host "Influnet Supabase schema"
Write-Host "------------------------"
Write-Host "1. Open SQL Editor: $ProjectUrl"
Write-Host "2. Paste and run (in order):"
Write-Host "     $Sql001"
Write-Host "     $Sql002"
Write-Host "     $Sql003"
Write-Host "     $Sql004"
Write-Host "     $Sql005"
Write-Host "     $Sql006"
Write-Host "     $Sql007"
Write-Host "     $Sql008"
Write-Host "     $Sql009"
Write-Host "     $Sql010"
Write-Host "     $Sql011"
Write-Host ""
Write-Host "Also in Dashboard → Authentication → Providers → enable Email"
Write-Host "Optional: Authentication → Providers → Email → disable 'Confirm email' for easier local testing"
Write-Host ""
Write-Host "001-011: profiles, messaging, RPC, presence/typing, projects, role fix, public profiles, business approval, business profile extras."

if (Test-Path $Sql001) {
  Write-Host "`n--- 001 preview (first 12 lines) ---"
  Get-Content $Sql001 -Head 12
}
