-- Campaign project tracking shared between business owner and influencer
-- Run after 001-005 migrations

CREATE TABLE IF NOT EXISTS public.campaign_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  counterparty_user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  budget NUMERIC,
  timeline TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  current_stage TEXT NOT NULL DEFAULT 'lead_received',
  stage_progress JSONB NOT NULL DEFAULT '{}'::jsonb,
  history JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT campaign_projects_no_self CHECK (owner_user_id <> counterparty_user_id)
);

CREATE INDEX IF NOT EXISTS campaign_projects_owner_idx
  ON public.campaign_projects (owner_user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS campaign_projects_counterparty_idx
  ON public.campaign_projects (counterparty_user_id, updated_at DESC);

DROP TRIGGER IF EXISTS campaign_projects_updated_at ON public.campaign_projects;
CREATE TRIGGER campaign_projects_updated_at
  BEFORE UPDATE ON public.campaign_projects
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.campaign_projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "campaign_projects_select_participant" ON public.campaign_projects;
CREATE POLICY "campaign_projects_select_participant"
  ON public.campaign_projects FOR SELECT
  TO authenticated
  USING (auth.uid() = owner_user_id OR auth.uid() = counterparty_user_id);

DROP POLICY IF EXISTS "campaign_projects_insert_owner" ON public.campaign_projects;
CREATE POLICY "campaign_projects_insert_owner"
  ON public.campaign_projects FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = owner_user_id);

DROP POLICY IF EXISTS "campaign_projects_update_participant" ON public.campaign_projects;
CREATE POLICY "campaign_projects_update_participant"
  ON public.campaign_projects FOR UPDATE
  TO authenticated
  USING (auth.uid() = owner_user_id OR auth.uid() = counterparty_user_id)
  WITH CHECK (auth.uid() = owner_user_id OR auth.uid() = counterparty_user_id);
