-- Business public profile: trust fields, reviews, portfolio, open campaigns

ALTER TABLE public.business_profiles
  ADD COLUMN IF NOT EXISTS founded_year TEXT,
  ADD COLUMN IF NOT EXISTS team_size TEXT,
  ADD COLUMN IF NOT EXISTS mission TEXT,
  ADD COLUMN IF NOT EXISTS products TEXT,
  ADD COLUMN IF NOT EXISTS services TEXT,
  ADD COLUMN IF NOT EXISTS brand_story TEXT,
  ADD COLUMN IF NOT EXISTS why_creators TEXT,
  ADD COLUMN IF NOT EXISTS creator_requirements JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS portfolio JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS open_campaigns JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS trusted_partner BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS website_verified BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.business_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  reviewer_user_id UUID REFERENCES public.profiles (id) ON DELETE SET NULL,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT,
  campaign_name TEXT,
  reviewer_name TEXT,
  reviewer_title TEXT,
  is_public BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS business_reviews_business_idx
  ON public.business_reviews (business_user_id, created_at DESC);

ALTER TABLE public.business_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_reviews_public_read ON public.business_reviews;
CREATE POLICY business_reviews_public_read
  ON public.business_reviews FOR SELECT
  TO anon, authenticated
  USING (is_public = true);

DROP POLICY IF EXISTS business_reviews_reviewer_insert ON public.business_reviews;
CREATE POLICY business_reviews_reviewer_insert
  ON public.business_reviews FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = reviewer_user_id);

-- Mark Influnet-verified when admin approves business
UPDATE public.business_profiles
SET verified_at = COALESCE(verified_at, now())
WHERE approval_status = 'approved' AND verified_at IS NULL;

CREATE OR REPLACE FUNCTION public.get_public_business(p_slug TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid UUID;
  ploc TEXT;
  pcreated TIMESTAMPTZ;
  pphone_verified BOOLEAN;
  bp public.business_profiles%ROWTYPE;
  needle TEXT;
  loc TEXT;
  review_rows JSONB;
  avg_rating NUMERIC;
  review_count INT;
BEGIN
  needle := lower(trim(coalesce(p_slug, '')));
  IF needle = '' THEN
    RETURN NULL;
  END IF;

  SELECT p.id, p.location, p.created_at, p.phone_verified
  INTO uid, ploc, pcreated, pphone_verified
  FROM public.profiles p
  INNER JOIN public.business_profiles b ON b.user_id = p.id
  WHERE p.role = 'business_owner'
    AND b.username IS NOT NULL
    AND lower(b.username) = needle
    AND b.approval_status = 'approved'
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  SELECT * INTO bp
  FROM public.business_profiles
  WHERE user_id = uid;

  loc := coalesce(
    nullif(trim(ploc), ''),
    CASE
      WHEN bp.city IS NOT NULL AND bp.state IS NOT NULL THEN trim(bp.city) || ', ' || trim(bp.state)
      WHEN bp.city IS NOT NULL THEN trim(bp.city)
      ELSE NULL
    END
  );

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', br.id,
      'rating', br.rating,
      'reviewText', br.review_text,
      'campaignName', br.campaign_name,
      'reviewerName', br.reviewer_name,
      'reviewerTitle', br.reviewer_title,
      'createdAt', br.created_at
    ) ORDER BY br.created_at DESC
  ), '[]'::jsonb),
  round(avg(br.rating)::numeric, 1),
  count(*)::int
  INTO review_rows, avg_rating, review_count
  FROM public.business_reviews br
  WHERE br.business_user_id = uid AND br.is_public = true;

  RETURN jsonb_build_object(
    'userId', uid,
    'companyName', bp.company_name,
    'username', bp.username,
    'profileSlug', bp.username,
    'tagline', bp.tagline,
    'companyDescription', bp.company_description,
    'logoUrl', bp.logo_url,
    'coverImageUrl', bp.cover_image_url,
    'industry', bp.industry,
    'businessType', bp.business_type,
    'website', bp.website,
    'location', loc,
    'city', bp.city,
    'state', bp.state,
    'instagramHandle', bp.instagram_handle,
    'facebookHandle', bp.facebook_handle,
    'linkedinHandle', bp.linkedin_handle,
    'marketingBudget', bp.marketing_budget,
    'collabPreferences', coalesce(bp.collab_preferences, '[]'::jsonb),
    'preferredCreatorNiches', coalesce(bp.preferred_creator_niches, '[]'::jsonb),
    'targetAudience', coalesce(bp.target_audience, '{}'::jsonb),
    'pastCampaigns', coalesce(bp.past_campaigns, '[]'::jsonb),
    'portfolio', coalesce(bp.portfolio, '[]'::jsonb),
    'openCampaigns', coalesce(bp.open_campaigns, '[]'::jsonb),
    'foundedYear', bp.founded_year,
    'teamSize', bp.team_size,
    'mission', bp.mission,
    'products', bp.products,
    'services', bp.services,
    'brandStory', bp.brand_story,
    'whyCreators', bp.why_creators,
    'creatorRequirements', coalesce(bp.creator_requirements, '{}'::jsonb),
    'isVerified', bp.approval_status = 'approved',
    'trustedPartner', coalesce(bp.trusted_partner, false),
    'verifiedAt', bp.verified_at,
    'websiteVerified', coalesce(bp.website_verified, false),
    'emailVerified', coalesce(bp.email_verified, false),
    'phoneVerified', coalesce(pphone_verified, false),
    'gstVerified', bp.gst_number IS NOT NULL AND length(trim(bp.gst_number)) >= 10,
    'memberSince', pcreated,
    'reviews', review_rows,
    'averageRating', avg_rating,
    'totalReviews', coalesce(review_count, 0)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_public_business(TEXT) TO anon, authenticated;
